//
//  EncourageQuoteData+en.swift
//  hold-it-ios
//

import Foundation

extension EncourageQuote {
    /// English encouragement quotes (~300)
    static let enQuotes: [String] = [
        // — Discipline & Self-Control —
        "Every act of restraint is a victory over yourself",
        "What you resist isn't desire — it's the path to a better you",
        "You are stronger than you think",
        "Small restraints today lead to great achievements tomorrow",
        "True freedom is not doing whatever you want, but choosing not to",
        "Discipline is freedom",
        "Every 'no' is a better 'yes' in disguise",
        "Slow and steady wins the race",
        "You're already on your way to becoming better",
        "Where persistence ends, habit begins",
        "A journey of a thousand miles begins with a single step",
        "Your future self will thank you for today's restraint",
        "Success is not final, failure is not fatal — it's the courage to continue that counts",
        "What you resist isn't happiness — it's momentary pleasure",
        "Small daily efforts lead to great results",
        "Self-discipline is the lowest-cost investment",
        "Those who master themselves can master their destiny",
        "You'll never know how strong you are until you push yourself",
        "Today's sweat is tomorrow's medal",
        "Restrain for a moment, benefit for a lifetime",
        "Self-control is the instinct of the strongest",
        "Every act of patience stores strength for the future",
        "If you can control yourself, you can control your life",
        "Knowing how to refuse gives you the power to choose",
        "Patience is bitter, but its fruit is sweet",
        "The more disciplined you are, the freer you become",
        "Control your desires — don't let them control you",
        "Every great action begins with a humble start",
        "Discipline isn't about dislike — it's about wanting the result more",
        "Today's discipline is tomorrow's best gift",
        // — Persistence & Perseverance —
        "Persistence is victory",
        "Hold on a little longer — a turning point may be near",
        "Dripping water hollows out stone — not through force, but persistence",
        "The most powerful force in the world is habit",
        "Good habits are life's interest; bad habits are life's debt",
        "There is only one kind of failure — giving up halfway",
        "You don't persist because you see hope — you see hope because you persist",
        "When you want to give up, remember why you started",
        "Every day you don't dance is a day wasted",
        "Life won't let down anyone who tries hard",
        "Hold fast like bamboo rooted in rock",
        "Stand firm against the winds from all directions",
        "The road is long, but arriving is possible; the task is hard, but completing it is certain",
        "Perseverance carves metal; giving up can't even break rotten wood",
        "Rome wasn't built in a day",
        "The finest steel is forged in the hottest fire",
        "With enough effort, even an iron rod can be ground into a needle",
        "A single leap doesn't cover ten steps; steady progress achieves the goal",
        "The harder the hardship, the stronger the resolve",
        "Age doesn't dim the fire of ambition",
        // — Confidence & Courage —
        "Believe in yourself — you're more amazing than you imagine",
        "Courage isn't the absence of fear — it's moving forward despite it",
        "You don't need to be perfect — you just need to start",
        "No one can go back and start over, but anyone can start now and create a new ending",
        "Just be yourself — everyone else is already taken",
        "You deserve everything you desire",
        "Don't forget why you started just because you've come so far",
        "You have infinite potential",
        "Don't let others' opinions dictate your life",
        "Just do your best — leave the rest to time",
        "Every great thing begins with a courageous first step",
        "Instead of gazing at the stars, become the one who shines",
        "You don't need to be born brave or gifted — just be earnest and diligent",
        "The darkest nights reveal the most beautiful stars",
        "No path in life is walked in vain — every step counts",
        "Your character carries the roads you've walked, the books you've read, and the people you've loved",
        "Behind every outstanding person is a period of silent dedication",
        "Headwinds are the best conditions for flying",
        "You don't need to be someone else — just be a better version of yourself",
        "When it feels difficult, you're climbing uphill",
        // — Growth & Change —
        "Growth is constantly saying goodbye to yesterday's self",
        "Being better today than yesterday is enough",
        "It's never too late to change — as long as you're willing to start",
        "Behind every outstanding person is a painful transformation",
        "Growth is a competition with yourself",
        "The best time to plant a tree was ten years ago; the second best time is now",
        "You can't start over from the past, but you can create a different ending starting now",
        "If those better than you are still trying, what right do you have to give up?",
        "Your current efforts are your future self's greatest confidence",
        "Don't choose comfort in the years meant for struggle",
        "Life's greatest regret isn't failure — it's 'I could have'",
        "Your efforts will eventually make you uniquely yourself",
        "All experiences are the wealth of growth",
        "Every fall is preparation for standing up stronger",
        "Everything you lose will return in another form",
        "Life won't disappoint anyone who takes it seriously",
        "What you want, time will eventually give you",
        "As long as you're willing to try, the world will surprise you",
        "Growth is constantly breaking out of your comfort zone",
        "Don't let your future self resent who you are now",
        // — Mindset & Calm —
        "Face the sun, and shadows fall behind you",
        "Smile at life, and life smiles back",
        "Your mindset determines your destiny",
        "Still waters run deep",
        "Move forward with gentleness and determination",
        "Don't worry — the best things arrive when you least expect them",
        "Stay passionate, chase the horizon",
        "Life is bright, and everything is lovely",
        "May your heart be as vast as the sea — holding the past and embracing the future",
        "The today you waste is the tomorrow someone who passed away longed for",
        "Mindset determines everything",
        "A calm lake never produced a skilled sailor",
        "Life is like tea — it won't be bitter forever, but it will be bitter for a while",
        "Your mood is decided by you alone",
        "Don't dwell on the past, don't crave the future — be present now",
        "Every worry has its remedy",
        "Happiness isn't about having more — it's about counting less",
        "Life is an attitude — relax a little and it gets better",
        "Worries have no roots — ignore them and they disappear",
        "A rich inner heart never fears solitude",
        // — Contentment & Gratitude —
        "Contentment isn't complacency — it's cherishing what you have",
        "Be grateful for every morning you wake up",
        "Simplicity is the ultimate sophistication",
        "Happiness isn't getting more — it's counting less",
        "The simplest happiness is the easiest to overlook",
        "Cherish the present — live in the moment",
        "You already have so much — you just haven't noticed yet",
        "Be grateful for every encounter in life",
        "Being alive is the greatest fortune",
        "The contented are the wealthiest",
        "The best things in life are free",
        "When you learn gratitude, you possess the whole world",
        "Don't wait until you lose something to cherish it",
        "Every new morning is a fresh beginning",
        "With a grateful heart, everything you meet is gentle",
        "Your life is someone else's dream",
        "Simple joys are the truest happiness",
        "All the good in the world comes from gratitude",
        "You have far more than you imagine",
        "Be grateful for every ordinary day",
        // — Time & Cherishing —
        "Time waits for no one — chase your dreams now",
        "Today is the youngest you'll ever be again",
        "Time won't let down anyone who quietly works hard",
        "Don't carry today's troubles into tomorrow",
        "The best time is right now",
        "Time is money",
        "Time flows on without stopping",
        "To cherish time is to cherish life",
        "Yesterday is gone, tomorrow isn't here — only today is in your hands",
        "Instead of regretting the past, seize the present",
        "Time is the best answer",
        "The rest of your life is precious — don't waste it",
        "Every day is a limited edition",
        "Right now, you're at the best age",
        "One today is worth two tomorrows",
        "Time will prove everything",
        "The most precious thing is always the present moment",
        "Don't fear the future, don't dwell on the past",
        "Life is short — why dwell on it?",
        "The years are long — worth the wait",
        // — Dreams & Pursuit —
        "Those with dreams stay forever young",
        "Dreams don't run away — you do",
        "Your heart determines your stage",
        "On the road to your dreams, you are the scenery",
        "Chase your dreams — what if they come true?",
        "Your dreams are worth your full effort",
        "Don't let anyone tell you your dreams are unrealistic",
        "The road of dreams is lonely, but the view at the end is beautiful",
        "Let your dreams illuminate reality",
        "Where there's a will, there's a way",
        "Dreams won't let down anyone who persists",
        "Where ambition leads, no distance is too far",
        "You're only one step away from your dream — that step is starting",
        "There's nothing you can't do — only things you haven't imagined",
        "Turn dreams into goals, and goals into actions",
        "Dreams come in all sizes — what matters is persistence",
        "With a dream in your heart, a path appears under your feet",
        "You're not alone on the road to your dreams",
        "Let every day bring you closer to your dream",
        "A life with dreams is a complete life",
        // — Action & Practice —
        "Action is the cure for fear",
        "Doing it once beats thinking about it a thousand times",
        "Without action, there will never be results",
        "A journey of a thousand miles begins with a single step",
        "Talk is cheap — action speaks",
        "The best time is now",
        "Don't wait until you're ready to start — start and you'll become ready",
        "Taking the first step means you've already beaten most people",
        "Just do it",
        "Hesitation leads to defeat; decisiveness leads to victory",
        "Act now — life doesn't have that many 'next times'",
        "Procrastination is the dream killer",
        "Do it today — don't wait for tomorrow",
        "Empty talk accomplishes nothing; hard work builds everything",
        "Don't be a giant in thought and a dwarf in action",
        "One action is worth a thousand empty thoughts",
        "Action is the best declaration",
        "You don't need everything ready — you just need the courage to set out",
        "Acting may bring regret, but not acting guarantees it",
        "I'd rather try and fail than never try at all",
        // — Wisdom & Thinking —
        "Thought is the seed of action",
        "Read ten thousand books, travel ten thousand miles",
        "Learning without thinking is useless; thinking without learning is dangerous",
        "Never stop learning",
        "Knowledge is power",
        "Among any three people, there must be a teacher for me",
        "Humility leads to progress; pride leads to backwardness",
        "Intelligence comes from learning; genius comes from accumulation",
        "Life is limited, but knowledge is limitless",
        "Review the old to understand the new",
        "Know yourself and your opponent, and you'll never lose",
        "Learning is like sailing against the current — not advancing means falling behind",
        "Don't fear being unable to learn — fear being unwilling to try",
        "Study broadly, question carefully, think deeply, discern clearly, practice earnestly",
        "Excellence comes from diligence; ruin comes from play",
        "Without long-term planning, troubles will soon arrive",
        "Time is more precious than gold, and gold can't buy time",
        "Good medicine tastes bitter; honest advice is hard to hear",
        "A fall into the pit, a gain in your wit",
        "Past experience, if not forgotten, is a guide for the future",
        // — Warmth & Healing —
        "You're amazing, truly",
        "Take a rest if you're tired — it's no big deal",
        "You've already done a great job",
        "Be gentle with yourself",
        "The world is big, and happiness is found in small things",
        "May you be treated gently by this world",
        "Love yourself well today too",
        "Give yourself a hug",
        "You deserve all the beauty in this world",
        "It's never too late",
        "It's okay — take your time",
        "You've worked so hard — don't be too hard on yourself",
        "Things will keep getting better",
        "Your existence itself is a ray of light",
        "It's okay to be imperfect — no one is",
        "You worked hard today — keep going tomorrow",
        "Your kindness will be seen by the world",
        "Every ordinary day deserves to be treated with care",
        "Life isn't perfect, but it's still worth loving",
        "The world is worth it — the future is promising",
        // — Independence & Strength —
        "Mountains fall — rely on yourself above all",
        "Independence is the best armor",
        "No one is your forever shelter — except yourself",
        "True strength comes from within",
        "Your resilience exceeds your imagination",
        "In the storm, be your own umbrella",
        "Even alone, live like an army",
        "Depend on no one — shine on your own",
        "Rely on yourself and you'll never lose",
        "You can be fine on your own",
        "An independent life is the freest",
        "Be your own sun — you don't need anyone else's light",
        "True strength is needing no one's dependence",
        "When you're strong enough, the whole world treats you kindly",
        "Your confidence comes from yourself",
        "Don't cling, don't settle",
        "The best sense of security is the kind you give yourself",
        "You don't need to please anyone",
        "Hold your destiny in your own hands",
        "Independence is the best posture",
        // — Simplicity & Focus —
        "Less is more",
        "Life needs subtraction",
        "Focus on the present — one thing at a time",
        "Spend your energy on what truly matters",
        "A focused mind can go the distance",
        "You don't need to do everything — doing one thing well is enough",
        "Simplify like autumn trees shedding leaves",
        "Let go, and life becomes lighter",
        "Subtract from life, add to happiness",
        "If you don't need it, let it go",
        "Focus is the rarest ability",
        "Doing one thing to perfection beats doing ten thousand things poorly",
        "Simplicity is the soul of wisdom",
        "What matters isn't how much you do — it's how well you do it",
        "Don't chase quantity — pursue quality",
        "Subtract from your life, add to your inner richness",
        "Let go of the unnecessary to make room for what you truly want",
        "Do one thing at a time, but do it better than anyone",
        "Minimalism is a kind of strength",
        "Think less, do more",
        // — Daily Joys & Little Happiness —
        "Sleeping early and rising early is the simplest form of discipline",
        "Eating well is the most basic act of self-love",
        "The sunshine is just right, and the breeze is gentle",
        "The clouds are beautiful today",
        "A glass of water, a ray of sunshine — life's little gifts",
        "Enjoy this moment of peace",
        "Occasionally stop and admire the scenery along the way",
        "Hidden in ordinary days are little moments of happiness",
        "Life isn't somewhere else — it's right here",
        "Feel every present moment with your heart",
        "Today's sky is blue just for you",
        "Happiness is nearby — we just often overlook it",
        "A deep breath, a smile — these are strength",
        "No rush — there's a long road ahead",
        "Life is made up of little moments of happiness",
        "Right now, you hold the whole world",
        "Find the extraordinary in the ordinary",
        "The warmth of a cup of tea can heal a day's fatigue",
        "A gentle breeze, peaceful years",
        "The warmth of everyday life soothes every heart",
        // — Encouragement & Inspiration —
        "You can do it — keep going",
        "Try a little harder, and everything will get better",
        "You're the best — don't doubt yourself",
        "Difficulties are temporary; giving up is permanent",
        "After the storm, there's always a rainbow",
        "It's always darkest before the dawn",
        "If winter comes, can spring be far behind?",
        "Beyond the dark clouds lies a bright village",
        "Through the winding paths, a bright new world appears",
        "Every person has their own unique talent",
        "Someday the wind will carry you to great heights",
        "Rise with the wind and soar to the heavens",
        "Past a fallen ship, a thousand sails still sail on",
        "Reach the summit, and the mountains below seem small",
        "Don't worry about the road ahead — the world knows your worth",
        "Where the sea meets the sky, that's the shore; at the mountain's peak, I stand supreme",
        "After a thousand washes, the gold finally shines through",
        "Nothing is impossible to a willing heart",
        "When you reach the mountain, there will be a road",
        "When the boat reaches the bridge, it will naturally straighten",
        // — Reflection & Awakening —
        "Knowing what you want is more important than anything",
        "Life's greatest enemy is yourself",
        "The hardest thing to conquer is your own laziness",
        "Only by examining yourself can you surpass yourself",
        "You can't change the wind, but you can adjust your sails",
        "If others can do it, so can you",
        "Don't cry over spilled milk",
        "Instead of complaining, change",
        "The today you complain about is the tomorrow someone else prays for",
        "Change what you can, accept what you can't",
        "True strength isn't conquering others — it's conquering yourself",
        "Your choices determine your life",
        "Don't lose yourself in others' judgments",
        "Knowing who you are is more important than who you become",
        "Understand yourself, and you'll go further",
        "Reflection is the ladder of progress",
        "You don't need to prove anything to anyone",
        "Just be yourself — you don't need to live up to others' expectations",
        "Your own feelings matter more than others' opinions",
        "Look within — the answer has always been in your heart",
        // — Hardship & Adversity —
        "No rainbow without rain",
        "Difficulties are blessings in disguise",
        "Adversity is the catalyst for growth",
        "There are no impassable obstacles — only impassable minds",
        "What doesn't kill you makes you stronger",
        "Hardship is the touchstone of life",
        "In the deepest despair, you'll find the most beautiful scenery",
        "After the storm, you'll emerge even stronger",
        "Setbacks aren't the end — they're turning points",
        "There are no dead ends in life — only turns",
        "The bitterness you've endured will light your way forward",
        "Hardships are gifts in disguise",
        "No suffering in life is in vain",
        "Grow in adversity, bloom in the storm",
        "All difficulties come to help you grow",
        "Rock bottom is just a phase of building strength",
        "The harder it gets, the more you must push forward",
        "In the headwind, learn to fly",
        "Nothing is built without breaking the old",
        "Hardship is the best teacher",
        // — Zen & Letting Go —
        "Going with the flow isn't giving up — it's doing your best and accepting the outcome",
        "Let go of attachments, and find freedom in this world",
        "There are cracks in everything — that's how the light gets in",
        "Don't be disturbed by the mind, don't be trapped by emotions",
        "Letting nature take its course is the best attitude toward life",
        "Life is like a journey — I am but a traveler",
        "Arriving like the wind and rain, departing like dust",
        "Try the new tea with fresh fire — enjoy poetry and wine while you can",
        "When you reach the end of the water, sit and watch the clouds rise",
        "Understanding the world is knowledge; mastering human relations is wisdom",
        "What is life like? Like a wild goose leaving footprints in the snow",
        "Where the heart finds peace, that is home",
        "One flower, one world; one leaf, one enlightenment",
        "Life is like a dream — raise a cup to the moon",
        "Falling flowers speak not; a person calm as chrysanthemums",
        "Unmoved by favor or disgrace, watching flowers bloom and fall in the courtyard",
        "Unmoved by coming or going, watching clouds roll and unroll in the sky",
        "Not pleased by gain, not saddened by loss",
        "Light clouds, gentle breeze, peaceful years",
        "When the heart is far, the place becomes serene",
        // — Moving Forward & Future —
        "The road ahead may be long, but the direction is right",
        "The future is promising — anything is possible",
        "The best is yet to come",
        "Walk toward the light",
        "You deserve a better tomorrow",
        "Keep moving forward — don't look back",
        "The future belongs to those who believe in the beauty of their dreams",
        "Your future is written by you",
        "Don't stop running, don't look back at where you've been",
        "The road behind holds no attachment — only the road ahead is worth anticipating",
        "Every step counts",
        "No step you take will be in vain",
        "The stars and the sea lie ahead",
        "The future will definitely be better",
        "Always believe that something wonderful is about to happen",
        "Your story has just begun",
        "Tomorrow is another day",
        "Treat every day as a new starting point",
        "There's light ahead and a path beneath your feet",
        "Don't chase the future, don't cling to the past",
        // — Life & Passion —
        "Passion can endure the longest years",
        "Live earnestly, and you'll find the candy life has hidden away",
        "While there's life, there's striving",
        "Live with everything you've got",
        "Life has no dress rehearsal — every day is a live show",
        "Live every day as if it were your last",
        "The best things in life are free",
        "Live fully, with sincerity and kindness",
        "Life is more than the present — there are poems and distant horizons",
        "Those who love life are rarely unlucky",
        "Only by living with all your might can you not let this life down",
        "Every day is a unique gift",
        "Enjoy every day of your life to the fullest",
        "Life is short — leave no regrets",
        "Turn your passion into habit",
        "Stay passionate about life, stay curious about the world",
        "Love life, and life will love you back",
        "Life is too short to leave room for regrets",
        "Living well is the greatest respect for life",
        "This world is worth your love",
    ]
}
