import 'package:flutter/material.dart';

class EncourageQuote {
  static List<String> get allQuotes {
    final locale = WidgetsBinding.instance.platformDispatcher.locale;
    final langCode = locale.languageCode;
    if (langCode == 'en') return enQuotes;
    if (langCode == 'ja') return jaQuotes;
    return zhHansQuotes;
  }

  static int get count => allQuotes.length;

  static int todayIndex() {
    final now = DateTime.now();
    final seed = now.year * 10000 + now.month * 100 + now.day;
    return seed.abs() % allQuotes.length;
  }

  static int randomIndex(int current) {
    if (allQuotes.length <= 1) return 0;
    int newIndex;
    do {
      newIndex = DateTime.now().millisecond % allQuotes.length;
    } while (newIndex == current);
    return newIndex;
  }

  static final List<String> zhHansQuotes = [
    '每一次忍住，都是对自己的一次胜利',
    '忍住的不是欲望，是通往更好自己的路',
    '你比自己想象的更强大',
    '今天忍住的小事，是明天成就的大事',
    '真正的自由，不是想做什么就做什么，而是不想做什么就不做',
    '自律者自由',
    '每一次说不，都是在说一个更好的是',
    '慢慢来，比较快',
    '你已经在变好的路上了',
    '坚持的尽头，是习惯的起点',
    '不积跬步，无以至千里',
    '当下的忍住，未来的你一定会感谢',
    '成功不是终点，失败不是末日，继续的勇气才最可贵',
    '你忍住的不是快乐，而是短暂的快感',
    '日拱一卒，功不唐捐',
    '自律是最低成本的投资',
    '能控制自己的人，才能掌握自己的命运',
    '不逼自己一把，你永远不知道自己有多优秀',
    '今天的汗水，是明天的勋章',
    '忍住一时，受益一生',
    '自我控制是最强者的本能',
    '每一次忍耐，都在为未来积蓄力量',
    '你能管住自己，就能管住人生',
    '懂得拒绝，才能拥有选择',
    '忍耐是痛苦的，但它的果实是甜蜜的',
    '越自律，越自由',
    '控制欲望，而不是被欲望控制',
    '一切伟大的行动，都有一个微不足道的开始',
    '自律不是因为不喜欢做，而是因为更想要那个结果',
    '你今天的自律，是明天最好的礼物',
    '坚持就是胜利',
    '再坚持一下，也许就是转机',
    '滴水穿石，不是力量大，而是功夫深',
    '世界上最可怕的力量是习惯',
    '好习惯是人生的利息，坏习惯是人生的债务',
    '失败只有一种，那就是半途而废',
    '不是因为看到希望才坚持，而是坚持了才看到希望',
    '当你想放弃的时候，想想你为什么出发',
    '每一个不曾起舞的日子，都是对生命的辜负',
    '生活不会亏待每一个努力的人',
    '相信自己，你比想象中更了不起',
    '勇敢不是不害怕，而是害怕了还继续前行',
    '你不需要完美，你只需要开始',
    '做自己就好，别的角色都有人了',
    '你值得拥有你想要的一切',
    '你有无限的可能',
    '不要让别人的看法左右你的人生',
    '你只管努力，剩下的交给时间',
    '所有的伟大，都源于一个勇敢的开始',
    '与其仰望星空，不如做那个发光的人',
    '成长就是不断和昨天的自己告别',
    '今天的你比昨天更好，这就够了',
    '改变从不会晚，只要你愿意开始',
    '种一棵树最好的时间是十年前，其次是现在',
    '你现在的努力，是未来的你最大的底气',
    '不要在该奋斗的年纪选择了安逸',
    '人生最大的遗憾，不是失败，而是我本可以',
    '你的努力，终将成就独一无二的自己',
    '心若向阳，无谓悲伤',
    '笑对人生，人生也会对你微笑',
    '你的心态，就是你的命运',
    '不必焦虑，最好的总会在不经意间出现',
    '保持热爱，奔赴山海',
    '生活明朗，万物可爱',
    '知足常乐，不是不思进取，而是懂得珍惜',
    '感恩每一个清醒的早晨',
    '简单是终极的复杂',
    '幸福不是得到更多，而是计较更少',
    '珍惜当下，活在当下',
    '你已经拥有了很多，只是你还没发现',
    '时间不等人，趁现在去追梦',
    '今天是你余生中最年轻的一天',
    '最好的时光，就是现在',
    '一寸光阴一寸金',
    '有梦想的人，永远年轻',
    '梦想不会逃跑，会逃跑的永远是自己',
    '心有多大，舞台就有多大',
    '你的梦想，值得你全力以赴',
    '行动是治愈恐惧的良药',
    '想一千次，不如做一次',
    '千里之行，始于足下',
    '最好的时机，就是现在',
    '踏出第一步，你就已经赢了大多数',
    '思考是行为的种子',
    '读万卷书，行万里路',
    '活到老，学到老',
    '知识就是力量',
    '你很棒，真的',
    '累了就歇一歇，没什么大不了的',
    '你已经做得很好了',
    '对自己温柔一点',
    '你值得世间一切美好',
    '一切都来得及',
    '靠山山会倒，靠自己最好',
    '独立是最好的铠甲',
    '自己强大，才是真的强大',
    '风雨中，做自己的伞',
    '少即是多',
    '人生需要做减法',
    '专注当下，一次只做一件事',
    '删繁就简三秋树',
    '早睡早起，是最简单的自律',
    '好好吃饭，是最基本的自爱',
    '阳光正好，微风不燥',
    '平凡的日子里，也藏着小确幸',
    '加油，你一定行',
    '再努力一下，一切都会变好',
    '你是最棒的，别怀疑自己',
    '风雨过后，一定有彩虹',
    '天生我材必有用',
    '长风破浪会有时',
    '世上无难事，只怕有心人',
    '知道自己想要什么，比什么都重要',
    '人生最大的敌人，是自己',
    '最难战胜的，是自己的惰性',
    '不经历风雨，怎么见彩虹',
    '那些打不倒你的，终将使你更强大',
    '在最深的绝望里，遇见最美的风景',
    '随缘不是得过且过，而是尽人事听天命',
    '放下执念，自在人间',
    '万物皆有裂痕，那是光照进来的地方',
    '前方的路，也许很远，但方向是对的',
    '未来可期，一切皆有可能',
    '最好的尚未到来',
    '你值得更好的明天',
    '往前走，别回头',
    '热爱可抵岁月漫长',
    '认真生活，就能找到生活藏起来的糖果',
    '生命不息，奋斗不止',
    '把每一天都当作最后一天来过',
  ];

  static final List<String> enQuotes = [
    'Every time you resist, you win a victory over yourself',
    'Self-discipline is the greatest gift you can give yourself',
    'You are stronger than you think',
    'Small steps lead to big changes',
    'The best time to start was yesterday. The next best time is now',
    'Discipline equals freedom',
    'Every no is a better yes',
    'Slow and steady wins the race',
    'You are already on the path to becoming better',
    'The end of persistence is the beginning of habit',
    'Rome was not built in a day',
    'Your future self will thank you for resisting today',
    'Success is not final, failure is not fatal',
    'You are not giving up happiness, just temporary pleasure',
    'Self-control is the strongest instinct',
    'Every moment of patience builds future strength',
    'Control your desires, do not be controlled by them',
    'All great actions have a humble beginning',
    'Your discipline today is your best gift tomorrow',
    'Persistence is victory',
    'Hold on a little longer, the turning point may be near',
    'Believe in yourself, you are more amazing than you think',
    'Courage is not the absence of fear, but moving forward despite it',
    'You do not need to be perfect, just start',
    'Be yourself, everyone else is taken',
    'You deserve everything you want',
    'You have infinite possibilities',
    'Do not let others dictate your life',
    'Just do your best, leave the rest to time',
    'All greatness begins with a brave start',
    'Growth is saying goodbye to yesterday\'s self',
    'You are better today than yesterday, that is enough',
    'It is never too late to change',
    'The best time to plant a tree was ten years ago, the second best is now',
    'Your current efforts are your future\'s greatest confidence',
    'Do not choose comfort when you should be striving',
    'Life\'s biggest regret is not failure, but "I could have"',
    'Your efforts will create a unique you',
    'Keep a positive mindset, and life will smile back',
    'Do not worry, the best things happen unexpectedly',
    'Stay passionate and chase your dreams',
    'Contentment is not lack of ambition, but knowing what to cherish',
    'Be grateful for every morning you wake up',
    'Simplicity is the ultimate sophistication',
    'Happiness comes from wanting less, not having more',
    'Cherish the present, live in the moment',
    'Time waits for no one, chase your dreams now',
    'Today is the youngest day of the rest of your life',
    'The best time is now',
    'Dreamers never grow old',
    'Dreams do not run away, people do',
    'Action is the cure for fear',
    'A journey of a thousand miles begins with a single step',
    'The best time to act is now',
    'Knowledge is power',
    'You are amazing, really',
    'Take a break when tired, it is okay',
    'You have done great',
    'Be gentle with yourself',
    'You deserve all the beauty in the world',
    'Everything is still possible',
    'Mountains may fall, rely on yourself',
    'Independence is the best armor',
    'True strength comes from within',
    'Less is more',
    'Focus on one thing at a time',
    'Early to bed and early to rise is the simplest discipline',
    'Eat well, love yourself',
    'The sun is shining, the breeze is gentle',
    'Even ordinary days hide little joys',
    'You can do it, keep going',
    'Try a little harder, everything will get better',
    'You are the best, do not doubt yourself',
    'After the storm comes the rainbow',
    'Every person has their worth',
    'There will be times when you ride the wind and cleave the waves',
    'Nothing is impossible to a willing heart',
    'Knowing what you want is more important than anything',
    'Your greatest enemy is yourself',
    'What does not kill you makes you stronger',
    'In the deepest despair, you find the most beautiful scenery',
    'Let go of attachments, live freely',
    'The cracks are where the light gets in',
    'The road ahead may be long, but the direction is right',
    'The future is promising',
    'The best is yet to come',
    'You deserve a better tomorrow',
    'Keep moving forward, do not look back',
    'Passion can withstand the long years',
    'Live seriously, and you will find life\'s hidden candy',
    'Live every day as if it were your last',
  ];

  static final List<String> jaQuotes = [
    '我慢するたびに、自分自身への勝利です',
    '自律は最高の贈り物です',
    'あなたは思っているより強いです',
    '小さな一歩が大きな変化を生みます',
    '始めるのに最適な時期は昨日でした。次に良い時期は今です',
    '規律は自由を生みます',
    'すべての「いいえ」は、より良い「はい」です',
    'ゆっくり着実に進みましょう',
    'あなたはすでに良くなる道を歩んでいます',
    '継続の終わりは、習慣の始まりです',
    'ローマは一日にして成らず',
    '未来のあなたは、今日の我慢に感謝するでしょう',
    '成功は最終ではなく、失敗は致命的ではありません',
    'あなたは幸福を諦めているのではなく、一時的な快楽を諦めているのです',
    '自制心は最強の本能です',
    '忍耐の瞬間が未来の力を築きます',
    '欲望をコントロールし、欲望にコントロールされないように',
    'すべての偉大な行動には、謙虚な始まりがあります',
    '今日の規律は、明日の最高の贈り物です',
    '継続は力なり',
    'もう少し続けて、転機は近いかもしれません',
    '自分を信じて、あなたは想像以上に素晴らしいです',
    '勇気は恐怖の不在ではなく、恐怖に直面して進むことです',
    '完璧である必要はありません、ただ始めればいいのです',
    '自分らしくあればいい、他の役はもう埋まっています',
    'あなたは望むすべてのものに値します',
    'あなたには無限の可能性があります',
    '他の人に人生を左右させないでください',
    '最善を尽くせば、残りは時間に任せましょう',
    'すべての偉大さは、勇敢な始まりから生まれます',
    '成長は昨日の自分に別れを告げることです',
    '今日のあなたは昨日より良い、それで十分です',
    '変わるのに遅すぎることはありません',
    '木を植えるのに最適な時期は10年前でした。次に良い時期は今です',
    '今の努力は、未来のあなたの最大の自信です',
    '努力すべき時に安楽を選ばないでください',
    '人生最大の後悔は失敗ではなく、「できたかもしれない」です',
    'あなたの努力は、唯一無二のあなたを創ります',
    '前向きな心構えを保てば、人生は笑い返します',
    '心配しないで、最良のことは予期せぬ時に起こります',
    '情熱を持って、夢を追いかけましょう',
    '知足は野望の欠如ではなく、大切なものを知ることです',
    '目覚める毎朝に感謝しましょう',
    'シンプルさは究極の洗練です',
    '幸福は多くを持つことではなく、少なく求めることから来ます',
    '今を大切に、今を生きましょう',
    '時は待たず、今すぐ夢を追いかけましょう',
    '今日は残りの人生で最も若い日です',
    '最良の時期は今です',
    '夢見る人は永遠に若いです',
    '夢は逃げません、逃げるのは人間です',
    '行動は恐怖の治療薬です',
    '千里の道も一歩から',
    '行動する最適な時期は今です',
    '知識は力なり',
    'あなたは素晴らしいです、本当に',
    '疲れたら休んでください、大丈夫です',
    'あなたはよくやっています',
    '自分に優しくしましょう',
    'あなたは世界のすべての美しさに値します',
    'すべてはまだ可能です',
    '山が崩れても、自分を信じましょう',
    '独立は最高の鎧です',
    '真の強さは内側から来ます',
    '少ないことは多いです',
    '一度に一つのことに集中しましょう',
    '早起きは最も簡単な規律です',
    'よく食べて、自分を愛しましょう',
    '太陽が輝き、風が穏やかです',
    '平凡な日々にも小さな幸せが隠れています',
    'あなたならできる、頑張ってください',
    'もう少し努力すれば、すべてが良くなります',
    'あなたは最高です、自分を疑わないでください',
    '嵐の後には虹が現れます',
    'すべての人に価値があります',
    'いつか風を切って波を裂く時が来ます',
    '意志あるところに道あり',
    '自分が何を望むか知ることは、何よりも重要です',
    '最大の敵は自分自身です',
    'あなたを倒せないものは、あなたを強くします',
    '最も深い絶望の中で、最も美しい景色に出会います',
    '執着を手放し、自由に生きましょう',
    'ひび割れは光が入る場所です',
    '前の道は長いかもしれませんが、方向は正しいです',
    '未来は有望です',
    '最良のものはまだ来ていません',
    'あなたはより良い明日に値します',
    '前に進み続け、振り返らないでください',
    '情熱は長い年月に耐えます',
    '真剣に生きれば、人生の隠れたキャンディーが見つかります',
    '毎日を最後の日として生きましょう',
  ];
}
